server:
  port: 8000

spring:
  profiles:
    # 配置文件 {dev-开发环境，test-测试环境，prod-生产环境}
    active: dev
  freemarker:
    check-template-location: false
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

# 七牛云
qiniu:
  path: file/
  avatar: avatar/
  # 文件大小 /M
  max-size: 20
  avatar-max-size: 5
  # 压缩图片
  compress-image: true

# 邮箱验证码有效时间/秒
code:
  expiration: 300

# 密码加密传输，前端公钥加密，后端私钥解密
rsa:
  public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCSBMqD7fSjc+37VL1qd9Aq/Q9fgwjH9SX/OpOBZu5W6N9RtWjF6fWhQqyljsykWsoL5ccuS/7YKmAdgZEd/fsM5Na0E8IwSFQIcO+h0BtfSxRa9GGKO6pPs8R7WbBeGT59+g44szUQYNzifwmDU6gY2pX4OaGRmkSgywDudiFxZwIDAQAB
  private-key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJIEyoPt9KNz7ftUvWp30Cr9D1+DCMf1Jf86k4Fm7lbo31G1aMXp9aFCrKWOzKRaygvlxy5L/tgqYB2BkR39+wzk1rQTwjBIVAhw76HQG19LFFr0YYo7qk+zxHtZsF4ZPn36DjizNRBg3OJ/CYNTqBjalfg5oZGaRKDLAO52IXFnAgMBAAECgYB9Ch9F1KpuoiLD27AMkScw+N2GQ9ZsLNDp/AY+hJ9Ky0YZWUisWoneGxNu/pbdk2V7xLvJOIi2IauG+OIFFe45rQ2fwCS41SnIIaXEDZ2MAcRNZYcsuDs63kdTKJEOYLPo2fH49Toki7e6g6vlLmpJSRTR2v02iPV5K9yFXJdO0QJBAO4ruW2JSk9UPAJkXb8MBqsccq8d3RZeexPOIc6LBtxwCxJ+VEnNXIl3fPAHqIkQp8v+NOsm7F5yJ9m7KicU6b8CQQCc8xNdblwtXP6kxb8hrfjW7L+7jpgwHv1nKlAvBiBNuVgwJYj5X1ZuHkkJsFlh+W4c9OyYHuxruSMJk/cAQ1JZAkB6P7k67xhUZbEzrR6tXFfj5oM7PYHo5HAaN1kE8jmAVoZoZK2RADb6XHmlnti0Gfd27rFs7hqvU7r+uGInk0VzAkAkoF0+ioicVX1fen5WH8FYdrtvy6Ecab79GlTIBIf5W22HHttORr9mx06IIk1ZndnijA3CmkTWBsh0bcFQoGVRAkBth80oGnG0Sb7l23T1sUvrCe7HPoA1gDX8HgVzODhAGI7a4dVr/g0Ulbg3C8YhyfI59JqR4XcjHNV0pbwFSowx
