version: '3'
services:

  mysql:
    image: mysql:5.7.16
    container_name: ${MYSQL_HOST}
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./volumes/${MYSQL_HOST}/data:/var/lib/mysql
      - ./volumes/${MYSQL_HOST}/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./volumes/${MYSQL_HOST}/source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
    ports:
      - ${MYSQL_PORT_OUT}:${MYSQL_PORT}

  redis:
    image: redis:6.2.0-alpine
    container_name: ${REDIS_HOST}
    restart: always
#    command: --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./volumes/${REDIS_HOST}/data:/data
      - ./volumes/${REDIS_HOST}/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./volumes/${REDIS_HOST}/logs:/logs
    environment:
      TZ: ${TZ}
    ports:
      - ${REDIS_PORT_OUT}:${REDIS_PORT}

  boot-admin:
    # 从阿里云镜像拉取
    # image: ${REGISTRY_URL}/${PROJECT_NAME}:latest
    image: ${PROJECT_NAME}:2.0
    container_name: ${PROJECT_NAME}
#    restart: always
    env_file: .env
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    depends_on:
      - mysql
      - redis
    volumes:
      - ./volumes/${PROJECT_NAME}/conf:/config
      - ./wait-for.sh:/wait-for.sh
    entrypoint: "sh /wait-for.sh boot-admin-mysql:3306 -- sh /wait-for.sh boot-admin-redis:6379 -- ${RUN_JAR}"
    environment:
      TZ: ${TZ}

networks:
  net:
    driver: bridge
